In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = '../data/processed/underpredicting_residuals.csv'

In [2]:
residual_df = pd.read_csv(data)

In [3]:
pd.set_option('display.max_columns', None )

In [4]:
residual_df.head(50)

,msno,hist_snap_dec_total_secs,hist_snap_dec_num_25,hist_snap_dec_num_50,hist_snap_dec_num_75,hist_snap_dec_num_985,hist_snap_dec_num_100,hist_snap_dec_num_unq,hist_snap_dec_total_songs,hist_snap_dec_days_active,hist_snap_dec_repeat_songs,hist_snap_jan_total_secs,hist_snap_jan_num_25,hist_snap_jan_num_50,hist_snap_jan_num_75,hist_snap_jan_num_985,hist_snap_jan_num_100,hist_snap_jan_num_unq,hist_snap_jan_total_songs,hist_snap_jan_days_active,hist_snap_jan_repeat_songs,hist_snap_feb_total_secs,hist_snap_feb_num_25,hist_snap_feb_num_50,hist_snap_feb_num_75,hist_snap_feb_num_985,hist_snap_feb_num_100,hist_snap_feb_num_unq,hist_snap_feb_total_songs,hist_snap_feb_days_active,hist_snap_feb_repeat_songs,hist_prior_2m_avg_songs,hist_prior_2m_avg_secs,hist_prior_2m_avg_days_active,hist_prior_2m_avg_unq,hist_prior_2m_avg_repeats,feb_songs_vs_prior_avg_delta,feb_secs_vs_prior_avg_delta,feb_active_days_vs_prior_avg_delta,feb_unq_vs_prior_avg_delta,feb_repeats_vs_prior_avg_delta,feb_vs_jan_songs_delta,feb_vs_jan_secs_delta,feb_vs_jan_active_days_delta,feb_vs_jan_unq_delta,feb_vs_jan_repeats_delta,jan_vs_dec_songs_delta,jan_vs_dec_secs_delta,jan_vs_dec_unq_delta,jan_vs_dec_repeats_delta,hist_3m_avg_songs,hist_3m_avg_secs,hist_3m_avg_days_active,hist_3m_total_active_days,hist_3m_avg_unq,hist_3m_avg_repeats,hist_3m_total_unq,hist_3m_total_repeats,feb_songs_vs_3m_avg_delta,feb_secs_vs_3m_avg_delta,feb_active_days_vs_3m_avg_delta,feb_unq_vs_3m_avg_delta,feb_repeats_vs_3m_avg_delta,trend_3m_slope_total_secs,trend_3m_slope_num_unq,trend_3m_slope_num_100,trend_3m_slope_days_active,trend_3m_slope_repeat_songs,total_songs_w-1,total_songs_w0,total_songs_w1,total_songs_w2,total_songs_w3,total_secs_w-1,total_secs_w0,total_secs_w1,total_secs_w2,total_secs_w3,num_100_w-1,num_100_w0,num_100_w1,num_100_w2,num_100_w3,num_unq_w-1,num_unq_w0,num_unq_w1,num_unq_w2,num_unq_w3,last_3d_secs,last_3d_songs,last_3d_unq,last_3d_active_days,songs_final_week_vs_prior_week_delta,secs_final_week_vs_prior_week_delta,completed_songs_final_week_vs_prior_week_delta,unique_songs_final_week_vs_prior_week_delta,avg_daily_songs_last_3d,avg_daily_secs_last_3d,songs_last_3d_vs_w0_daily_delta,secs_last_3d_vs_w0_daily_delta,last_3d_active_rate,last2wk_vs_last_month_numunq_avg_diff,hist_ex_latest_mode_payment_plan_days,hist_ex_latest_mode_actual_amount_paid,hist_ex_latest_mean_payment_plan_days,hist_ex_latest_mean_actual_amount_paid,hist_ex_latest_mean_plan_list_price,hist_ex_latest_mean_coverage_days,hist_latest_payment_plan_days,hist_latest_plan_list_price,hist_latest_actual_amount_paid,hist_latest_coverage_days,latest_plan_days_vs_historical_mode_delta,latest_amount_paid_vs_historical_mode_delta,latest_amount_paid_vs_historical_mean_delta,latest_coverage_days_vs_historical_mean_delta,hist_latest_is_cancel,hist_latest_is_auto_renew,hist_total_cancels,hist_transaction_count,hist_payment_method_change,hist_tenure_days,hist_recency_days,hist_cancel_rate,payment_method_mode,city,bd,gender,registered_via,is_churn,bd_missing,time_active,predicted_proba
0,h5Zop82aISspPM8BDCAzKkMlwOR+WHE1pSA5SRwqr9s=,340354.470,870.0,159.0,104.0,107.0,1191.0,2105.0,2431.0,47.0,326.0,785640.20000,847.0,150.0,169.0,180.0,2813.0,3584.0,4159.0,72.0,575.0,8.321532e+05,1304.0,267.0,198.0,211.0,2901.0,3986.0,4881.0,70.0,895.0,3295.0,562997.3000,59.5,2844.5,450.5,1586.0,269155.8800,10.5,1141.5,444.5,722.0,46513.00000,-2.0,402.0,320.0,1728.0,445285.720000,1479.0,249.0,3823.666700,652715.94000,63.000000,189.0,3225.000000,598.666700,9675.0,1796.0,1057.333300,179437.25000,7.000000,761.000000,296.333300,245899.360000,940.5,855.0,11.5,284.5,3556.0,370.0,422.0,179.0,354.0,606784.000000,59177.171875,78535.828125,38472.238281,49183.988281,2112.0,201.0,287.0,132.0,169.0,3022.0,278.0,239.0,168.0,279.0,24424.7540,205.0,176.0,1.0,-52.0,-19358.65600,-86.0,39.0,68.333336,8141.584500,15.476193,-312.29720,0.333333,-25.072727,30.0,149.0,31.904762,164.761900,157.66667,34.571430,30.0,149.0,149.0,30.0,0.0,0.0,-15.761905,-4.571429,0.0,0.0,0.0,22.0,2.0,772.0,16.0,0.000000,38,22,21,female,3,1,0,1842,0.133346
1,CasIiQGb92BZRI8CGuoAxLvVgcIZY/lH8coFOIjqCPE=,900769.000,395.0,116.0,53.0,57.0,3560.0,2329.0,4181.0,61.0,1852.0,586460.60000,287.0,110.0,59.0,63.0,2371.0,1384.0,2890.0,56.0,1506.0,4.043631e+05,278.0,107.0,44.0,43.0,1609.0,1566.0,2081.0,51.0,515.0,3535.5,743614.8000,58.5,1856.5,1679.0,-1454.5,-339251.7500,-7.5,-290.5,-1164.0,-809.0,-182097.56000,-5.0,182.0,-991.0,-1291.0,-314308.380000,-945.0,-346.0,3050.666700,630530.90000,56.000000,168.0,1759.666600,1291.000000,5279.0,3873.0,-969.666750,-226167.81000,-5.000000,-193.666630,-776.000000,-248202.970000,-381.5,-975.5,-5.0,-668.5,1490.0,236.0,89.0,103.0,163.0,296469.062500,46183.167969,10437.049805,20609.501953,30664.285156,1186.0,192.0,37.0,72.0,122.0,1091.0,178.0,72.0,82.0,143.0,37549.7270,180.0,132.0,1.0,147.0,35746.11700,155.0,106.0,60.000000,12516.575000,26.285715,5918.98000,0.333333,-17.831165,30.0,149.0,30.000000,149.000000,149.00000,31.900000,30.0,149.0,149.0,30.0,0.0,0.0,0.000000,-1.900000,0.0,0.0,0.0,21.0,1.0,623.0,13.0,0.000000,38,1,-1,missing,3,1,1,1376,0.140323
2,eEiiW9JrDPS5P15dsMpk6rcfgXwCBWnwqsbcU586ZfU=,163188.610,89.0,29.0,14.0,10.0,686.0,455.0,828.0,37.0,373.0,120475.16400,48.0,12.0,6.0,15.0,500.0,395.0,581.0,33.0,186.0,1.777095e+05,71.0,34.0,20.0,13.0,725.0,565.0,863.0,36.0,298.0,704.5,141831.8900,35.0,425.0,279.5,158.5,35877.6250,1.0,140.0,18.5,282.0,57234.35000,3.0,170.0,112.0,-247.0,-42713.445000,-60.0,-187.0,757.333300,153791.10000,35.333332,106.0,471.666660,285.666660,1415.0,857.0,105.666690,23918.42200,0.666668,93.333340,12.333343,7260.453000,55.0,19.5,-0.5,-37.5,227.0,126.0,274.0,124.0,112.0,43201.105469,28268.400391,60170.101562,22744.328125,23325.578125,170.0,122.0,249.0,89.0,95.0,146.0,83.0,148.0,93.0,95.0,8986.0840,39.0,22.0,1.0,-148.0,-31901.70100,-127.0,-65.0,13.000000,2995.361300,-5.000000,-1042.98160,0.333333,1.037879,30.0,149.0,28.230770,137.538470,137.53847,28.230770,30.0,149.0,149.0,30.0,0.0,0.0,11.461538,1.769231,0.0,0.0,0.0,14.0,2.0,680.0,25.0,0.000000,38,1,-1,missing,9,1,1,828,0.194956
3,Zz/V0MZcCdtc/MIXFlql6mIKRjtz+5TUkAlPwoIHvaE=,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,30.0,149.0,30.000000,149.000000,149.00000,31.480000,30.0,149.0,149.0,29.0,0.0,0.0,0.000000,-2.480000,0.0,1.0,0.0,26.0,1.0,762.0,13.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.038064
4,Ltn9FlDM2NhV4Gxu/HcAZStzIxvc8P+PN/QzuiALGKE=,818192.300,417.0,121.0,70.0,67.0,3160.0,2180.0,3835.0,32.0,1655.0,971281.70000,623.0,183.0,104.0,146.0,3663.0,3086.0,4719.0,60.0,1633.0,7.002370e+05,260.0,44.0,54.0,49.0,2670.0,1612.0,3077.0,43.0,1465.0,4277.0,894737.0000,46.0,2633.0,1644.0,-1200.0,-194500.0000,-3.0,-1021.0,-179.0,-1642.0,-271044.70000,-17.0,-1474.0,-168.0,884.0,153089.380000,906.0,-22.0,3877.000000,829903.70000,45.000000,135.0,2292.666700,1584.333400,6878.0,4753.0,-800.000000,-129666.69000,-2.000000,-680.666750,-119.333374,-58977.656000,-284.0,-245.0,5.5,-95.0,500.0,1007.0,906.0,224.0,440.0,104583.351562,238862.640625,211982.093750,53566.207031,91242.664062,346.0,927.0,808.0,209.0,380.0,428.0,448.0,328.0,106.0,302.0,75812.3200,313.0,136.0,1.0,101.0,26880.54700,119.0,120.0,104.333336,25270.773000,-39.523808,-8852.46100,0.333333,-13.898166,30.0,149.0,23.375000,130.375000,111.75000,29.750000,30.0,149.0,149.0,30.0,0.0,0.0,18.625000,0.250000,0.0,0.0,0.0,9.0,1.0,748.0,18.0,0.000000,38,6,20,female,9,1,0,930,0.173543
5,vscOA7k0o7kzj6bgwRcVUjxp+IE0O0xcPIbBtGHSYjc=,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,30.0,149.0,21.428572,149.000000,106.42857,30.428572,30.0,149.0,149.0,31.0,0.0,0.0,0.000000,0.571429,0.0,1.0,0.0,22.0,1.0,700.0,0.0,0.000000,34,-1,-1,missing,-1,1,1,1500,0.009157
6,HuipM9S2/2QLFUv9BeJCjqQLMiRmwLIYqWYCgkA4r9U=,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,30.0,99.0,30.000000,99.000000,99.00000,30.466667,30.0,99.0,99.0,28.0,0.0,0.0,0.000000,-2.466667,0.0,1.0,0.0,16.0,1.0,457.0,25.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.011894
7,6KtCZZCGnP74UFNXoVR51ZEOBCBpUaIdijc1OnpktVE=,122401.305,51.0,8.0,11.0,6.0,450.0,447.0,526.0,23.0,79.0,96359.77000,486.0,43.0,24.0,37.0,287.0,805.0,877.0,19.0,72.0,7.044699e+04,111.0,16.0,25.0,15.0,241.0,253.0,408.0,15.0,155.0,701.5,109380.5400,21.0,626.0,75.5,-293.5,-38933.5470,-6.0,-373.0,79.5,-469.0,-25912.78100,-4.0,-552.0,83.0,351.0,-26041.531000,358.0,-7.0,603.666700,96402.69000,19.000000,57.0,501.666660,102.000000,1505.0,306.0,-195.666690,-25955.69500,-4.000000,-248.666660,53.000000,-25977.156000,-97.0,-104.5,-4.0,38.0,0.0,245.0,127.0,0.0,36.0,0.000000,40983.578125,23471.550781,0.000000,5991.865234,0.0,147.0,80.0,0.0,14.0,0.0,165.0,56.0,0.0,32.0,16190.7840,108.0,98.0,1.0,118.0,17512.02700,67.0,109.0,36.000000,5396.928000,1.000000,-457.86865,0.333333,3.527273,30.0,149.0,30.000000,149.000000,149.00000,30.500000,30.0,149.0,149.0,28.0,0.0,0.0,0.000000,-2.500000,0.0,1.0,0.0,5.0,1.0,122.0,27.0,0.000000,41,1,-1,missing,7,1,1,149,0.123431
8,exxI4lMB98XPB8iAertKCvCkUzzNjrOtMJVsYKvpINA=,319894.160,359.0,81.0,46.0,58.0,1105.0,1499.0,1649.0,42.0,150.0,335112.16000,464.0,134.0,67.0,128.0,1028.0,1380.0,1821.0,54.0,441.0,4.939043e+05,394.0,123.0,81.0,68.0,1752.0,1855.0,2418.0,66.0,563.0,1735.0,327503.1600,48.0,1439.5,295.5,683.0,166401.1900,18.0,415.5,267.5,597.0,158792.19000,12.0,475.0,122.0,172.0,15218.000000,-119.0,291.0,1962.666600,382970.22000,54.000000,162.0,1578.000000,384.666660,4734.0,1154.0,455.333370,110934.12500,12.000000,277.000000,178.333340,87005.090000,178.0,323.5,12.0,206.5,1934.0,177.0,173.0,16.0,118.0,401749.468750,38445.957031,32599.843750,2703.787109,18405.320312,1472.0,121.0,109.0,4.0,46.0,1430.0,142.0,164.0,14.0,105.0,20817.8950,87.0,66.0,1.0,4.0,5846.11330,12.0,-22.0,29.000000,6939.298300,3.714286,1447.01880,0.333333,-13.967583,30.0,149.0,30.000000,149.000000,149.00000,40.533333,30.0,149.0,149.0,50.0,0.0,0.0,0.000000,9.466666,0.0,1.0,0.0,16.0,2.0,758.0,28.0,0.000000,39,13,20,female,9,1,0,1284,0.026722
9,x8246fDWanPb+cR0jlwj/m+OeU5DPJ4nMeh2f8BKUI8=,13242.936,144.0,15.0,3.0,5.0,42.0,181.0,209.0,7.0,28.0,12537.38100,82.0,13.0,3.0,3.0,42.0,125.0,143.0,7.0,18.0,2.509439e+03,2.0,0.0,0.0,0.0,11.0,13.0,13.0,3.0,0.0,176.0,12890.1580,7.0,153.0,23.0,-163.0,-10380.7190,-4.0,-140.0,-23.0,-130.0,-10027.94100,-4.0,-112.0,-18.0,-66.0,-705.554700,-56.0,-10.0,121.666664,9429.91800,5.666666,17.0,106.333336,15.333333,319.0,46.0,-108.666664,-6920.47900,-2.666666,-93.333336,-15.333333,-5366.748000,-84.0,-15.5,-2.0,-14.0,0.0,0.0,4.0,6.0,3.0,0.000000,0.000000,913.304016,1323.000000,273.135010,0.0,0.0,4.0,6.0,1.0,0.0,0.0,4.0,6.0,3.0,0.0000,0.0,0.0,0.0,-4.0,-913.30400,-4.0,-4.0,0.000000,0.000000,0.000000,0.00000,0.000000,-17.655914,30.0,99.0,30.000000,99.000000,99.00000,30.636364,30.0,99.0,99.0,28.0,0.0,0.0,0.000000,-2.636364,0.0,1.0,0.0,12.0,1.0,337.0,26.0,0.000000,41,1,-1,missing,7,1,1,363,0.094465
10,lrolwor514WSeAbA5zkek8Z47ju7xhLMTODxaqpxWAs=,25828.607,37.0,3.0,5.0,3.0,96.0,102.0,144.0,8.0,42.0,15867.66200,29.0,2.0,1.0,0.0,63.0,78.0,95.0,8.0,17.0,2.601370e+04,6.0,1.0,4.0,2.0,105.0,107.0,118.0,13.0,11.0,119.5,20848.1350,8.0,90.0,29.5,-1.5,5165.5664,5.0,17.0,-18.5,23.0,10146.03900,5.0,29.0,-6.0,-49.0,-9960.945000,-24.0,-25.0,119.000000,22569.99000,9.666667,29.0,95.666664,23.333334,287.0,70.0,-1.000000,3443.71100,3.333333,11.333336,-12.333334,92.546875,2.5,4.5,2.5,-15.5,81.0,5.0,12.0,19.0,1.0,18263.062500,1001.453003,2635.831055,3863.468018,249.888000,76.0,4.0,9.0,15.0,1.0,71.0,5.0,11.0,19.0,1.0,0.0000,0.0,0.0,0.0,-7.0,-1634.37800,-5.0,-6.0,0.000000,0.000000,-0.714286,-143.06471,0.000000,-6.427351,30.0,99.0,30.000000,99.000000,99.00000,30.416666,30.0,99.0,99.0,28.0,0.0,0.0,0.000000,-2.416667,0.0,1.0,0.0,13.0,1.0,365.0,24.0,0.000000,41,1,-1,missing,7,1,1,389,0.034730
11,pVMCYhKPSOYMa7o+xvtAspgMOOPXXudaamGAYpS5UXA=,19112.088,25.0,19.0,17.0,46.0,18.0,112.0,125.0,14.0,13.0,53428.53000,68.0,42.0,50.0,123.0,64.0,300.0,347.0,34.0,47.0,6.020150e+04,65.0,29.0,45.0,87.0,133.0,312.0,359.0,29.0,47.0,236.0,36270.3100,24.0,206.0,30.0,123.0,23931.1910,5.0,106.0,17.0,12.0,6772.96880,-5.0,12.0,0.0,222.0,34316.445000,188.0,34.0,277.000000,44247.37500,25.666666,77.0,241.333330,35.666668,724.0,107.0,82.000000,15954.12500,3.333334,70.666670,11.333332,20544.707000,100.0,57.5,7.5,17.0,77.0,75.0,28.0,55.0,124.0,11325.828125,12560.936523,4316.228027,10298.624023,21699.875000,18.0,18.0,10.0,28.0,59.0,69.0,67.0,23.0,45.0,108.0,9592.8030,60.0,52.0,1.0,47.0,8244.70900,8.0,44.0,20.000000,3197.600800,9.285714,1403.18130,0.333333,-2.833103,30.0,180.0,30.000000,168.000000,168.00000,30.300000,30.0,180.0,180.0,30.0,0.0,0.0,12.000000,-0.300000,0.0,0.0,0.0,11.0,1.0,487.0,21.0,0.000000,36,1,-1,missing,4,1,1,508,0.169609
12,8TQAb0UK99zrBnu99083So7Pt2ihHxN9HKGrcEZiS3o=,13777.756,1.0,3.0,1.0,17.0,95.0,98.0,117.0,3.0,19.0,967.02000,2.0,0.0,0.0,0.0,4.0,6.0,6.0,2.0,0.0,1.094118e+04,3.0,0.0,0.0,1.0,52.0,56.0,56.0,4.0,0.0,61.5,7372.3877,2.5,52.0,9.5,-5.5,3568.7940,1.5,4.0,-9.5,50.0,9974.16200,2.0,50.0,0.0,-111.0,-12810.736000,-92.0,-19.0,59.666668,8561.98600,3.000000,9.0,53.333332,6.333334,160.0,19.0,-3.666668,2379.19530,1.000000,2.666668,-6.333334,-1418.287100,-21.0,-21.5,0.5,-9.5,2.0,54.0,0.0,0.0,0.0,267.410004,10673.771484,0.000000,0.000000,0.000000,1.0,51.0,0.0,0.0,0.0,2.0,54.0,0.0,0.0,0.0,10673.7710,54.0,54.0,1.0,54.0,10673.77100,51.0,54.0,18.000000,3557.923800,10.285714,2033.09940,0.333333,12.142858,30.0,149.0,21.428572,149.000000,106.42857,30.428572,30.0,149.0,149.0,31.0,0.0,0.0,0.000000,0.571429,0.0,1.0,0.0,22.0,1.0,700.0,0.0,0.000000,33,22,37,female,9,1,0,3811,0.020835
13,wl5qylsUU3Z4RPyyfZFeDXchwQMptosrzTKoNbGFkas=,78582.610,140.0,61.0,43.0,29.0,242.0,440.0,515.0,34.0,75.0,98446.50000,330.0,69.0,55.0,53.0,286.0,652.0,793.0,50.0,141.0,1.597137e+05,264.0,93.0,77.0,53.0,510.0,852.0,997.0,48.0,145.0,654.0,88514.5550,42.0,546.0,108.0,343.0,71199.1800,6.0,306.0,37.0,204.0,61267.23400,-2.0,200.0,4.0,278.0,19863.890000,212.0,66.0,768.333300,112247.62000,44.000000,132.0,648.000000,120.333336,1944.0,361.0,228.666690,47466.11700,4.000000,204.000000,24.666664,40565.562000,206.0,134.0,7.0,35.0,419.0,123.0,130.0,158.0,167.0,68571.562500,20533.646484,19120.613281,26117.115234,25370.812500,210.0,68.0,48.0,98.0,86.0,373.0,107.0,112.0,117.0,143.0,619.2940,3.0,3.0,1.0,-7.0,1413.03320,20.0,-5.0,1.000000,206.431340,-16.571428,-2726.94680,0.333333,-3.393518,30.0,149.0,28.636364,149.000000,142.22728,30.181818,30.0,149.0,149.0,39.0,0.0,0.0,0.000000,8.818182,0.0,0.0,0.0,23.0,1.0,732.0,32.0,0.000000,38,8,22,male,9,1,0,1935,0.175141
14,+WWwYTd9tZ7vS41XOrBOMW6xabxBOrAF1zd04GDtY3I=,73518.120,329.0,41.0,36.0,66.0,184.0,573.0,656.0,20.0,83.0,51652.07400,126.0,16.0,10.0,23.0,183.0,301.0,358.0,21.0,57.0,5.448685e+04,39.0,11.0,6.0,11.0,198.0,236.0,265.0,11.0,29.0,507.0,62585.0940,20.5,437.0,70.0,-242.0,-8098.2420,-9.5,-201.0,-41.0,-93.0,2834.77730,-10.0,-65.0,-28.0,-298.0,-21866.043000,-272.0,-26.0,426.333340,59885.68000,17.333334,52.0,370.000000,56.333332,1110.0,169.0,-161.333340,-5398.82800,-6.333334,-134.000000,-27.333332,-9515.633000,-168.5,7.0,-4.5,-27.0,0.0,156.0,6.0,9.0,94.0,0.000000,33386.824219,1106.047974,1355.911011,18638.066406,0.0,124.0,4.0,4.0,66.0,0.0,132.0,4.0,9.0,91.0,32020.2300,149.0,125.0,1.0,150.0,32280.77500,120.0,128.0,49.666668,10673.410000,27.380953,5903.86400,0.333333,3.781036,30.0,149.0,30.000000,124.166664,149.00000,29.833334,30.0,149.0,149.0,27.0,0.0,0.0,24.833334,-2.833333,0.0,1.0,0.0,7.0,1.0,185.0,24.0,0.000000,40,13,25,male,4,1,0,265,0.045549
15,BxeFRaU+dYmZ/j7Y6hoquuOma90F4sa3N2yH7o/NVe4=,208438.170,199.0,67.0,50.0,35.0,728.0,969.0,1079.0,52.0,110.0,178866.10000,210.0,96.0,50.0,46.0,581.0,884.0,983.0,75.0,99.0,2.552485e+05,276.0,80.0,57.0,41.0,912.0,1243.0,1366.0,64.0,123.0,1031.0,193652.1200,63.5,926.5,104.5,335.0,61596.4200,0.5,316.5,18.5,383.0,76382.45000,-11.0,359.0,24.0,-96.0,-29572.078000,-85.0,-11.0,1142.666600,214184.27000,63.666668,191.0,1032.000000,110.666664,3096.0,332.0,223.333370,41064.28000,0.333332,211.000000,12.333336,23405.188000,137.0,92.0,6.0,6.5,773.0,51.0,224.0,143.0,175.0,152666.234375,8865.677734,40371.328125,25042.703125,28302.585938,546.0,29.0,154.0,85.0,98.0,719.0,50.0,201.0,116.0,157.0,4396.2210,23.0,22.0,1.0,-173.0,-31505.65000,-125.0,-151.0,7.666666,1465.407100,0.380952,198.88171,0.333333,-5.527319,30.0,149.0,29.000000,143.269230,143.26923,28.692308,30.0,149.0,149.0,30.0,0.0,0.0,5.730769,1.307692,0.0,1.0,1.0,27.0,1.0,765.0,14.0,0.037037,40,22,27,female,3,1,0,967,0.049342
16,lM/lrIrpqOYkx0CiNanp+UfUG/rEaYoCMq9TFOWEQtk=,462507.880,936.0,90.0,51.0,64.0,1677.0,2298.0,2818.0,51.0,520.0,896331.60000,1462.0,169.0,125.0,112.0,3282.0,3704.0,5150.0,89.0,1446.0,5.569613e+05,1044.0,99.0,78.0,84.0,2033.0,2739.0,3338.0,72.0,599.0,3984.0,679419.7500,70.0,3001.0,983.0,-646.0,-122458.4400,2.0,-262.0,-384.0,-1812.0,-339370.30000,-17.0,-965.0,-847.0,2332.0,433823.750000,1406.0,926.0,3768.666700,638600.25000,70.666664,212.0,2913.666700,855.000000,8741.0,2565.0,-430.666750,-81638.94000,1.333336,-174.666750,-256.000000,47226.720000,220.5,178.0,10.5,39.5,2638.0,158.0,236.0,148.0,158.0,451972.968750,26782.625000,27918.417969,21737.835938,28549.468750,1676.0,89.0,81.0,80.0,107.0,2251.0,130.0,120.0,115.0,123.0,11934.5700,63.0,58.0,1.0,-78.0,-1135.79300,8.0,10.0,21.000000,3978.190200,-1.571428,152.10090,0.333333,-28.510101,30.0,149.0,21.428572,149.000000,106.42857,30.428572,30.0,149.0,149.0,31.0,0.0,0.0,0.000000,0.571429,0.0,1.0,0.0,22.0,1.0,700.0,0.0,0.000000,34,13,33,female,9,1,0,3198,0.008422
17,t3+uhrKHa7WxXYwUMz7s6BqFNXkxVQATRD8A/ZF6rKE=,18444.762,6.0,2.0,1.0,0.0,63.0,64.0,72.0,7.0,8.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.976838e+03,4.0,0.0,1.0,0.0,5.0,10.0,10.0,2.0,0.0,36.0,9222.3810,3.5,32.0,4.0,-26.0,-7245.5430,-1.5,-22.0,-4.0,10.0,1976.83790,2.0,10.0,0.0,-72.0,-18444.762000,-64.0,-8.0,27.333334,6807.19970,3.000000,9.0,24.666666,2.666667,74.0,8.0,-17.333334,-4830.36200,-1.000000,-14.666666,-2.666667,-8233.962000,-27.0,-29.0,-2.5,-4.0,0.0,3.0,0.0,7.0,0.0,0.000000,559.044983,0.000000,1417.792969,0.000000,0.0,2.0,0.0,3.0,0.0,0.0,3.0,0.0,7.0,0.0,559.0450,3.0,3.0,1.0,3.0,559.04500,2.0,3.0,1.000000,186.348330,0.571429,106.48476,0.333333,-5.875000,30.0,99.0,30.000000,99.000000,99.00000,30.636364,30.0,99.0,99.0,28.0,0.0,0.0,0.000000,-2.636364,0.0,1.0,0.0,12.0,1.0,337.0,18.0,0.000000,41,1,-1,missing,7,1,1,355,0.105660

In [5]:
residual_df.shape

(5681, 133)

In [6]:
check_df = residual_df.loc[residual_df['city'] == -1]

In [7]:
check_df.head(50)

,msno,hist_snap_dec_total_secs,hist_snap_dec_num_25,hist_snap_dec_num_50,hist_snap_dec_num_75,hist_snap_dec_num_985,hist_snap_dec_num_100,hist_snap_dec_num_unq,hist_snap_dec_total_songs,hist_snap_dec_days_active,hist_snap_dec_repeat_songs,hist_snap_jan_total_secs,hist_snap_jan_num_25,hist_snap_jan_num_50,hist_snap_jan_num_75,hist_snap_jan_num_985,hist_snap_jan_num_100,hist_snap_jan_num_unq,hist_snap_jan_total_songs,hist_snap_jan_days_active,hist_snap_jan_repeat_songs,hist_snap_feb_total_secs,hist_snap_feb_num_25,hist_snap_feb_num_50,hist_snap_feb_num_75,hist_snap_feb_num_985,hist_snap_feb_num_100,hist_snap_feb_num_unq,hist_snap_feb_total_songs,hist_snap_feb_days_active,hist_snap_feb_repeat_songs,hist_prior_2m_avg_songs,hist_prior_2m_avg_secs,hist_prior_2m_avg_days_active,hist_prior_2m_avg_unq,hist_prior_2m_avg_repeats,feb_songs_vs_prior_avg_delta,feb_secs_vs_prior_avg_delta,feb_active_days_vs_prior_avg_delta,feb_unq_vs_prior_avg_delta,feb_repeats_vs_prior_avg_delta,feb_vs_jan_songs_delta,feb_vs_jan_secs_delta,feb_vs_jan_active_days_delta,feb_vs_jan_unq_delta,feb_vs_jan_repeats_delta,jan_vs_dec_songs_delta,jan_vs_dec_secs_delta,jan_vs_dec_unq_delta,jan_vs_dec_repeats_delta,hist_3m_avg_songs,hist_3m_avg_secs,hist_3m_avg_days_active,hist_3m_total_active_days,hist_3m_avg_unq,hist_3m_avg_repeats,hist_3m_total_unq,hist_3m_total_repeats,feb_songs_vs_3m_avg_delta,feb_secs_vs_3m_avg_delta,feb_active_days_vs_3m_avg_delta,feb_unq_vs_3m_avg_delta,feb_repeats_vs_3m_avg_delta,trend_3m_slope_total_secs,trend_3m_slope_num_unq,trend_3m_slope_num_100,trend_3m_slope_days_active,trend_3m_slope_repeat_songs,total_songs_w-1,total_songs_w0,total_songs_w1,total_songs_w2,total_songs_w3,total_secs_w-1,total_secs_w0,total_secs_w1,total_secs_w2,total_secs_w3,num_100_w-1,num_100_w0,num_100_w1,num_100_w2,num_100_w3,num_unq_w-1,num_unq_w0,num_unq_w1,num_unq_w2,num_unq_w3,last_3d_secs,last_3d_songs,last_3d_unq,last_3d_active_days,songs_final_week_vs_prior_week_delta,secs_final_week_vs_prior_week_delta,completed_songs_final_week_vs_prior_week_delta,unique_songs_final_week_vs_prior_week_delta,avg_daily_songs_last_3d,avg_daily_secs_last_3d,songs_last_3d_vs_w0_daily_delta,secs_last_3d_vs_w0_daily_delta,last_3d_active_rate,last2wk_vs_last_month_numunq_avg_diff,hist_ex_latest_mode_payment_plan_days,hist_ex_latest_mode_actual_amount_paid,hist_ex_latest_mean_payment_plan_days,hist_ex_latest_mean_actual_amount_paid,hist_ex_latest_mean_plan_list_price,hist_ex_latest_mean_coverage_days,hist_latest_payment_plan_days,hist_latest_plan_list_price,hist_latest_actual_amount_paid,hist_latest_coverage_days,latest_plan_days_vs_historical_mode_delta,latest_amount_paid_vs_historical_mode_delta,latest_amount_paid_vs_historical_mean_delta,latest_coverage_days_vs_historical_mean_delta,hist_latest_is_cancel,hist_latest_is_auto_renew,hist_total_cancels,hist_transaction_count,hist_payment_method_change,hist_tenure_days,hist_recency_days,hist_cancel_rate,payment_method_mode,city,bd,gender,registered_via,is_churn,bd_missing,time_active,predicted_proba
3,Zz/V0MZcCdtc/MIXFlql6mIKRjtz+5TUkAlPwoIHvaE=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,149.0,30.000000,149.00000,149.00000,31.480000,30.0,149.0,149.0,29.0,0.0,0.0,0.00000,-2.480000,0.0,1.0,0.0,26.0,1.0,762.0,13.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.038064
5,vscOA7k0o7kzj6bgwRcVUjxp+IE0O0xcPIbBtGHSYjc=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,149.0,21.428572,149.00000,106.42857,30.428572,30.0,149.0,149.0,31.0,0.0,0.0,0.00000,0.571429,0.0,1.0,0.0,22.0,1.0,700.0,0.0,0.000000,34,-1,-1,missing,-1,1,1,1500,0.009157
6,HuipM9S2/2QLFUv9BeJCjqQLMiRmwLIYqWYCgkA4r9U=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.466667,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.466667,0.0,1.0,0.0,16.0,1.0,457.0,25.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.011894
32,c4pe1PKcFYJ1lecxBjHgU9hyzm2n7/FQH9jkHHsAK/4=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.545454,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.545454,0.0,1.0,0.0,12.0,1.0,336.0,3.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.119976
39,zk8i0KCZ63yqJK4FFsp9Z0mpO9GTtBbW99lG83BKK6M=,147896.64,271.0,70.0,49.0,40.0,514.0,644.0,944.0,25.0,300.0,137689.66,288.0,72.0,43.0,35.0,481.0,563.0,919.0,26.0,356.0,52282.848,107.0,20.0,24.0,15.0,177.0,250.0,343.0,15.0,93.0,931.5,142793.16,25.5,603.5,328.0,-588.5,-90510.31,-10.5,-353.5,-235.0,-576.0,-85406.81,-11.0,-313.0,-263.0,-25.0,-10206.984,-81.0,56.0,735.3333,112623.05,22.0,66.0,485.66666,249.66667,1457.0,749.0,-392.3333,-60340.2,-7.0,-235.66666,-156.66667,-47806.9,-197.0,-168.5,-5.0,-103.5,0.0,159.0,68.0,71.0,45.0,0.0,25405.125,9220.407227,10756.275391,6901.041992,0.0,87.0,31.0,35.0,24.0,0.0,107.0,62.0,55.0,26.0,13959.918,86.0,57.0,1.0,91.0,16184.718,56.0,45.0,28.666666,4653.306,5.95238,1024.0026,0.333333,0.516239,30.0,129.0,30.000000,129.00000,129.00000,29.600000,30.0,129.0,129.0,27.0,0.0,0.0,0.00000,-2.600000,0.0,1.0,0.0,6.0,1.0,153.0,14.0,0.000000,30,-1,-1,missing,-1,1,1,1500,0.034305
42,EgUgIU4KxqsTRTtJkDnDlvNMu+YvdH5s/AmVtxNDUY8=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.636364,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.636364,0.0,1.0,0.0,12.0,1.0,337.0,2.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.111955
57,A1UdXEtc44XQgONRtZNE3edFeqrPcCIN0/6z/Bwy7CY=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.571428,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.571429,0.0,1.0,0.0,8.0,1.0,214.0,16.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.009631
71,kf/VmzWft5thlzMWuxJqVZJz9jWJGHA59eTuxImdZJ4=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.562500,30.0,99.0,99.0,31.0,0.0,0.0,0.00000,0.437500,0.0,1.0,0.0,17.0,1.0,519.0,0.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.012361
77,rfKXk4HWbE0dxA5YYFXXm1p/0Q/Q16pJP+QqefsALfU=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.500000,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.500000,0.0,1.0,0.0,5.0,1.0,122.0,12.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.008523
101,w/2lDWHncgro2+r/mNgQQlhmQmXHe7eg+bapn2u/p28=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.578947,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.578947,0.0,1.0,0.0,20.0,1.0,581.0,25.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.012991
120,aNccXW1P2yVgkAix6T7aweTkyJ55iaFUH3zJW2L9tFw=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,149.0,30.000000,0.00000,0.00000,30.000000,30.0,100.0,100.0,27.0,0.0,0.0,0.00000,0.000000,0.0,1.0,0.0,1.0,0.0,0.0,5.0,0.000000,-1,-1,-1,missing,-1,1,1,1500,0.039289
121,G5pyT2TCbQE6ExJOIeoRwX6IpKI8S+iBkwhOO1r0nkU=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.600000,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.600000,0.0,1.0,0.0,11.0,1.0,337.0,23.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.093268
125,G5r721z7sGrjlzSJ/O07UT5uoq/qTx6t0+kkdkKeAHQ=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,149.0,30.000000,0.00000,0.00000,30.000000,30.0,129.0,129.0,27.0,0.0,0.0,0.00000,0.000000,0.0,1.0,0.0,1.0,0.0,0.0,12.0,0.000000,-1,-1,-1,missing,-1,1,1,1500,0.246737
142,K/ucuuQsgX6nXEsYIvaHSgImOgwdX/PwK4YcrBXI4WM=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,149.0,30.000000,0.00000,0.00000,30.000000,30.0,100.0,100.0,27.0,0.0,0.0,0.00000,0.000000,0.0,1.0,0.0,1.0,0.0,0.0,20.0,0.000000,-1,-1,-1,missing,-1,1,1,1500,0.042353
166,+HEhU4Z44VA0RGO5KNnOfhG/y514B66eKh/auR+309Y=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.714285,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.714286,0.0,1.0,0.0,8.0,1.0,215.0,3.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.008877
173,Nw4IeRw79y2svEnTJnw1d5yQTlmceDzdkkDILmog4xE=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,149.0,30.000000,149.00000,149.00000,30.000000,30.0,149.0,149.0,28.0,0.0,0.0,0.00000,-2.000000,0.0,1.0,0.0,2.0,1.0,30.0,14.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.074894
178,KnKF1AAP5XbOMK99+uNtad+waqgUoKyEjrCMGJ1Hm0o=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,149.0,30.000000,0.00000,0.00000,30.000000,30.0,129.0,129.0,27.0,0.0,0.0,0.00000,0.000000,0.0,1.0,0.0,1.0,0.0,0.0,22.0,0.000000,-1,-1,-1,missing,-1,1,1,1500,0.249438
179,93QSIoN2MLa3tHz4R4ycrijn+D4dzEvyOOZGIvKjm2Y=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.500000,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.500000,0.0,1.0,0.0,3.0,1.0,61.0,13.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.008742
228,5bId0xEAXjWD2Ocz9GQPydDPHk99Ieer25/wdjSrdEM=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.500000,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.500000,0.0,1.0,0.0,17.0,1.0,488.0,14.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.011388
231,ZPGc50vdcxHOtDJ1Uvo2EchB3fgL4aIcXVhnKJgiWfk=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.636364,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.636364,0.0,1.0,0.0,12.0,1.0,337.0,3.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.111955
239,RZrX4fDfEWKAcmSnCeYEXamVo+ctLHDvMBgPD/8+/J4=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.461538,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.461539,0.0,1.0,0.0,14.0,1.0,396.0,17.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.046117
252,AHOFsVIxflcFvbhwTxmeMllkyQ1BFhNXPjP9bpwIvqI=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,99.0,30.000000,99.00000,99.00000,30.500000,30.0,99.0,99.0,28.0,0.0,0.0,0.00000,-2.500000,0.0,1.0,0.0,13.0,1.0,366.0,24.0,0.000000,41,-1,-1,missing,-1,1,1,1500,0.050399
272,O3MWV4V+9i1lVB7JVrJdvp82WljFwfEWwHjvJq1dO3E=,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0000,0.00,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000,0.00000,0.0000,0.000000,0.000000,30.0,149.0,30.000000,0.00000,0.00000,30.000000,30.0,100.0,100.0,27.0,0.0,0.0,0.00000,0.000000,0.0,1.0,0.0,1.0,0.0,0.0,23.0,0.000000,-1,-1,-1,missing,-1,1,1,1500,0.042439

In [8]:
check_df.shape

(664, 133)

In [9]:
check_df.hist_latest_is_auto_renew.sum()

np.float64(664.0)

In [10]:
# Force Jupyter to display all 132 rows completely without truncating
pd.set_option('display.max_rows', 200)

# 1. Isolate and transpose your specific user row
user_1_id = 'h5Zop82aISspPM8BDCAzKkMlwOR+WHE1pSA5SRwqr9s='
user_1_profile = residual_df.loc[residual_df['msno'] == user_1_id].T

# 2. Rename the column header to the user's ID for clarity
user_1_profile.columns = ['User_Value']

# 3. Print the entire feature vector
user_1_profile;

In [11]:
# Force Jupyter to display all 132 rows completely without truncating
pd.set_option('display.max_rows', 200)

# 1. Isolate and transpose your specific user row
user_2_id = 'CasIiQGb92BZRI8CGuoAxLvVgcIZY/lH8coFOIjqCPE='
user_2_profile = residual_df.loc[residual_df['msno'] == user_1_id].T

# 2. Rename the column header to the user's ID for clarity
user_2_profile.columns = ['User_Value']

# 3. Print the entire feature vector
user_2_profile;

In [12]:
residual_df.hist_latest_is_auto_renew.sum()

np.float64(4039.0)

In [13]:
residual_df.loc[(residual_df['hist_latest_is_auto_renew'] == 0) & (residual_df['hist_snap_feb_days_active'] > 40) ].shape

(690, 133)

In [14]:
residual_df['residuals'] = residual_df['is_churn'] - residual_df['predicted_proba']

/tmp/ipykernel_9918/1879129436.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  residual_df['residuals'] = residual_df['is_churn'] - residual_df['predicted_proba']

In [15]:
import seaborn as sns

In [16]:
residual_df.select_dtypes(include=['number']).corr()['residuals'].sort_values(ascending=False)

residuals                                         1.000000
hist_latest_is_auto_renew                         0.776915
hist_transaction_count                            0.320714
hist_tenure_days                                  0.235045
payment_method_mode                               0.167598
time_active                                       0.161633
bd_missing                                        0.103987
hist_total_cancels                                0.090549
registered_via                                    0.068702
hist_cancel_rate                                  0.044880
hist_ex_latest_mean_coverage_days                 0.034909
total_secs_w-1                                    0.026774
num_100_w-1                                       0.023870
trend_3m_slope_days_active                        0.020076
feb_vs_jan_repeats_delta                          0.019704
feb_repeats_vs_prior_avg_delta                    0.018567
feb_repeats_vs_3m_avg_delta                       0.018567
hist_latest_coverage_days                         0.018178
feb_vs_jan_songs_delta                            0.016619
num_unq_w-1                                       0.015671
total_songs_w-1                                   0.015550
songs_last_3d_vs_w0_daily_delta                   0.013577
feb_songs_vs_prior_avg_delta                      0.013339
feb_songs_vs_3m_avg_delta                         0.013339
trend_3m_slope_repeat_songs                       0.012466
hist_ex_latest_mode_payment_plan_days             0.012151
feb_vs_jan_unq_delta                              0.010277
feb_secs_vs_prior_avg_delta                       0.010276
feb_secs_vs_3m_avg_delta                          0.010276
trend_3m_slope_total_secs                         0.010180
feb_unq_vs_prior_avg_delta                        0.007048
feb_unq_vs_3m_avg_delta                           0.007048
feb_vs_jan_secs_delta                             0.004350
jan_vs_dec_secs_delta                             0.004122
secs_last_3d_vs_w0_daily_delta                    0.004054
trend_3m_slope_num_unq                            0.002748
trend_3m_slope_num_100                            0.000507
jan_vs_dec_repeats_delta                         -0.002722
feb_active_days_vs_prior_avg_delta               -0.003141
feb_active_days_vs_3m_avg_delta                  -0.003141
hist_snap_jan_total_secs                         -0.004350
jan_vs_dec_songs_delta                           -0.004856
jan_vs_dec_unq_delta                             -0.005224
bd                                               -0.008851
hist_snap_dec_total_secs                         -0.010180
hist_prior_2m_avg_secs                           -0.010276
hist_3m_avg_secs                                 -0.010276
latest_amount_paid_vs_historical_mean_delta      -0.011865
latest_plan_days_vs_historical_mode_delta        -0.012151
latest_coverage_days_vs_historical_mean_delta    -0.031175
hist_ex_latest_mean_payment_plan_days            -0.033407
hist_snap_feb_repeat_songs                       -0.033579
feb_vs_jan_active_days_delta                     -0.034764
hist_snap_jan_repeat_songs                       -0.039487
latest_amount_paid_vs_historical_mode_delta      -0.040648
hist_3m_total_repeats                            -0.043541
hist_3m_avg_repeats                              -0.043541
hist_snap_jan_num_100                            -0.044839
hist_prior_2m_avg_repeats                        -0.046720
hist_snap_feb_num_100                            -0.047201
last2wk_vs_last_month_numunq_avg_diff            -0.047891
hist_snap_feb_total_secs                         -0.050560
hist_snap_dec_repeat_songs                       -0.050653
unique_songs_final_week_vs_prior_week_delta      -0.051992
completed_songs_final_week_vs_prior_week_delta   -0.053253
secs_final_week_vs_prior_week_delta              -0.055570
songs_final_week_vs_prior_week_delta             -0.055782
hist_snap_dec_num_100                            -0.057725
hist_snap_jan_days_active                        -0.064618
city                                             -0.066114
hist_snap_feb_total_songs                        -0.070638
hist_snap_jan_total_songs                        -0.071623
hist_latest_is_cancel                            -0.076528
hist_snap_jan_num_unq                            -0.079055
hist_3m_avg_songs                                -0.080249
hist_snap_feb_num_unq                            -0.081401
hist_prior_2m_avg_songs                          -0.082404
hist_snap_feb_days_active                        -0.083990
hist_payment_method_change                       -0.087403
hist_prior_2m_avg_days_active                    -0.087556
hist_3m_avg_days_active                          -0.087628
hist_3m_total_active_days                        -0.087628
hist_snap_feb_num_985                            -0.088674
hist_snap_dec_total_songs                        -0.088978
hist_3m_avg_unq                                  -0.089311
hist_3m_total_unq                                -0.089311
hist_prior_2m_avg_unq                            -0.090244
hist_ex_latest_mean_actual_amount_paid           -0.092829
hist_snap_dec_num_unq                            -0.096804
hist_snap_jan_num_985                            -0.100413
hist_recency_days                                -0.100966
hist_snap_feb_num_25                             -0.104134
hist_snap_feb_num_75                             -0.105642
hist_snap_jan_num_75                             -0.106847
num_100_w2                                       -0.107424
hist_snap_jan_num_25                             -0.108681
num_100_w1                                       -0.112054
hist_snap_dec_days_active                        -0.112061
hist_snap_dec_num_985                            -0.112688
total_secs_w2                                    -0.116097
hist_snap_feb_num_50                             -0.116671
hist_ex_latest_mean_plan_list_price              -0.117903
hist_snap_jan_num_50                             -0.118222
num_100_w3                                       -0.119273
hist_snap_dec_num_25                             -0.122087
num_100_w0                                       -0.123128
total_secs_w1                                    -0.123388
total_secs_w3                                    -0.128723
hist_snap_dec_num_75                             -0.128888
hist_ex_latest_mode_actual_amount_paid           -0.133466
total_secs_w0                                    -0.134320
last_3d_secs                                     -0.136952
avg_daily_secs_last_3d                           -0.136952
total_songs_w2                                   -0.143373
hist_snap_dec_num_50                             -0.147291
total_songs_w3                                   -0.151710
total_songs_w1                                   -0.152588
last_3d_songs                                    -0.155261
avg_daily_songs_last_3d                          -0.155261
total_songs_w0                                   -0.158758
num_unq_w3                                       -0.169031
num_unq_w2                                       -0.169052
last_3d_unq                                      -0.171192
num_unq_w1                                       -0.178863
num_unq_w0                                       -0.180653
last_3d_active_rate                              -0.208953
last_3d_active_days                              -0.208953
hist_latest_actual_amount_paid                   -0.297007
hist_latest_plan_list_price                      -0.344529
predicted_proba                                  -1.000000
hist_latest_payment_plan_days                          NaN
is_churn                                               NaN
Name: residuals, dtype: float64

In [1]:
#'1.  After analysis of the residuals that were most underpredictiing churn, there were 2 problems that became apperrant immediately'
#    'The first are ghost accounts these have no user logs(no usage for the three months I look at), no transactional history whatsoever,'
#    'but they were subject to expiry in march 2017 like all other examples, I incorrectly imputed them with median values thinking '
#    'they can not have no transactions or user history whatsoever, this was a mistake all the columns of these ghost acoount are under an autorenewal,'
#    'they all have a specific types of registered_via_id i believe these are third party contracted accounts part of pre paid phone plans,'
#    'the owners do not use the app or open it even once so they dont have any member data, no transactions , no user logs just an auto renewal flag, probably being paid at'
#    'a wholesale value by a phone or service provided each month until the third party plan runs out.'
# fix: remove median imputation for these people flag them as ghost accounts there is no way to discern when they will churn no signal is given just an abrupt but we know most don't around 97%.
#'2.' 'The correlation analysis of residuals and the independent variables exposed another issue autorenew was drowning out the nuances of each customer the model'
#      saw autorenew is = 1 and said the customer will remain it would take too many splits for the tree model to realise that even if auto renew is on but they are no longer'
#     'engaging and their activity rate is lowering they will churn'
# fix: interaction with auto_renew combining engagement with auto_renew to create binary signals that will boost the model's 
#      performance and counter the drowning of the other features by auto_renew
#'3'. 'There are not enough calculations of volatility and disorganised usage this is missing signal and the ratios that are part of the current features the 3 day ones'
#     'are corrupted, calculated using data from the last 3 days defeating the purpose of the ratio'
#fix : must remove last 3 days from comparison data for the 3 days

In [18]:
residual_df.last_3d_secs.dtype

dtype('float64')

In [19]:
low = residual_df.hist_ex_latest_mode_actual_amount_paid.quantile(q=0.25)

In [20]:
non_zero =  residual_df.loc[residual_df.last_3d_secs > 0]

In [21]:
print(low)

129.0

In [22]:
non_zero.hist_ex_latest_mode_actual_amount_paid.quantile(0.8)

np.float64(150.0)

In [23]:
residual_df.loc[residual_df['hist_ex_latest_mode_actual_amount_paid'] <= 129].shape

(1492, 134)

In [24]:
non_zero.select_dtypes(include=['number']).corr()['residuals'].sort_values(ascending=False)

residuals                                         1.000000
hist_latest_is_auto_renew                         0.851027
hist_transaction_count                            0.303341
hist_tenure_days                                  0.214951
registered_via                                    0.214107
time_active                                       0.166526
hist_total_cancels                                0.123010
total_secs_w-1                                    0.098245
hist_snap_jan_days_active                         0.094047
num_unq_w-1                                       0.092726
total_songs_w-1                                   0.089712
num_100_w-1                                       0.089134
hist_cancel_rate                                  0.077561
hist_3m_avg_days_active                           0.076852
hist_3m_total_active_days                         0.076852
hist_snap_feb_days_active                         0.076541
hist_prior_2m_avg_days_active                     0.074338
bd                                                0.073008
payment_method_mode                               0.072217
trend_3m_slope_days_active                        0.068125
hist_ex_latest_mean_coverage_days                 0.053690
jan_vs_dec_secs_delta                             0.050370
hist_snap_jan_total_secs                          0.046685
hist_snap_jan_num_100                             0.045055
hist_snap_feb_total_secs                          0.044141
hist_3m_avg_secs                                  0.041571
jan_vs_dec_songs_delta                            0.040419
jan_vs_dec_unq_delta                              0.040218
hist_snap_dec_days_active                         0.040054
hist_snap_feb_num_100                             0.039765
hist_prior_2m_avg_secs                            0.038444
trend_3m_slope_total_secs                         0.036643
hist_latest_coverage_days                         0.036019
bd_missing                                        0.035571
hist_snap_feb_repeat_songs                        0.035353
trend_3m_slope_repeat_songs                       0.031027
hist_3m_avg_repeats                               0.029488
hist_3m_total_repeats                             0.029488
trend_3m_slope_num_unq                            0.028880
hist_snap_jan_repeat_songs                        0.028612
hist_snap_dec_num_100                             0.028124
jan_vs_dec_repeats_delta                          0.027348
hist_snap_jan_total_songs                         0.027253
hist_snap_feb_total_songs                         0.026912
trend_3m_slope_num_100                            0.025857
hist_prior_2m_avg_repeats                         0.024638
feb_repeats_vs_prior_avg_delta                    0.024279
feb_repeats_vs_3m_avg_delta                       0.024279
hist_snap_dec_total_secs                          0.024092
hist_3m_avg_songs                                 0.022138
hist_snap_jan_num_unq                             0.021475
feb_songs_vs_prior_avg_delta                      0.020350
feb_songs_vs_3m_avg_delta                         0.020350
hist_prior_2m_avg_songs                           0.018510
feb_secs_vs_prior_avg_delta                       0.017528
feb_secs_vs_3m_avg_delta                          0.017528
hist_snap_feb_num_unq                             0.017436
hist_ex_latest_mode_payment_plan_days             0.017151
hist_snap_dec_repeat_songs                        0.016268
hist_3m_avg_unq                                   0.014152
hist_3m_total_unq                                 0.014152
feb_active_days_vs_prior_avg_delta                0.014038
feb_active_days_vs_3m_avg_delta                   0.014038
feb_unq_vs_prior_avg_delta                        0.013374
feb_unq_vs_3m_avg_delta                           0.013374
hist_prior_2m_avg_unq                             0.011737
feb_vs_jan_repeats_delta                          0.007084
hist_snap_dec_total_songs                         0.005334
city                                              0.001921
last_3d_active_rate                               0.000855
last_3d_active_days                               0.000855
hist_snap_dec_num_unq                            -0.001767
feb_vs_jan_songs_delta                           -0.005184
songs_last_3d_vs_w0_daily_delta                  -0.007680
hist_snap_feb_num_985                            -0.011603
feb_vs_jan_unq_delta                             -0.011796
latest_amount_paid_vs_historical_mean_delta      -0.012434
feb_vs_jan_secs_delta                            -0.015032
hist_ex_latest_mean_payment_plan_days            -0.015842
secs_last_3d_vs_w0_daily_delta                   -0.016485
latest_plan_days_vs_historical_mode_delta        -0.017151
unique_songs_final_week_vs_prior_week_delta      -0.017582
completed_songs_final_week_vs_prior_week_delta   -0.017755
songs_final_week_vs_prior_week_delta             -0.018783
hist_snap_feb_num_75                             -0.019104
secs_final_week_vs_prior_week_delta              -0.019137
hist_snap_jan_num_75                             -0.022041
hist_snap_feb_num_25                             -0.022323
hist_snap_jan_num_985                            -0.026501
latest_amount_paid_vs_historical_mode_delta      -0.029049
hist_snap_jan_num_25                             -0.030218
num_100_w2                                       -0.035776
num_100_w1                                       -0.036799
hist_snap_feb_num_50                             -0.040096
num_100_w0                                       -0.040989
total_secs_w2                                    -0.041030
hist_snap_jan_num_50                             -0.041739
total_secs_w1                                    -0.043252
latest_coverage_days_vs_historical_mean_delta    -0.044119
hist_snap_dec_num_985                            -0.046003
num_100_w3                                       -0.046351
hist_snap_dec_num_25                             -0.047027
total_secs_w0                                    -0.047622
hist_snap_dec_num_75                             -0.047689
total_secs_w3                                    -0.050664
last_3d_secs                                     -0.056518
avg_daily_secs_last_3d                           -0.056518
last2wk_vs_last_month_numunq_avg_diff            -0.060700
hist_recency_days                                -0.064540
hist_latest_is_cancel                            -0.066833
total_songs_w2                                   -0.067248
feb_vs_jan_active_days_delta                     -0.069491
total_songs_w1                                   -0.071187
total_songs_w0                                   -0.071200
total_songs_w3                                   -0.071405
last_3d_songs                                    -0.074792
avg_daily_songs_last_3d                          -0.074792
hist_snap_dec_num_50                             -0.078279
num_unq_w3                                       -0.090186
last_3d_unq                                      -0.091744
hist_ex_latest_mean_actual_amount_paid           -0.092045
hist_payment_method_change                       -0.093603
num_unq_w2                                       -0.094127
num_unq_w0                                       -0.094875
num_unq_w1                                       -0.098329
hist_ex_latest_mean_plan_list_price              -0.106758
hist_ex_latest_mode_actual_amount_paid           -0.108079
hist_latest_actual_amount_paid                   -0.272674
hist_latest_plan_list_price                      -0.340689
predicted_proba                                  -1.000000
hist_latest_payment_plan_days                          NaN
is_churn                                               NaN
Name: residuals, dtype: float64

In [25]:
check_df.time_active.value_counts()

time_active
1500    664
Name: count, dtype: int64

In [28]:
print(residual_df.hist_transaction_count.quantile(0.75))

21.0