In [1]:
import pandas as pd
import numpy as np

In [2]:
Data = '../data/raw/transactions.csv'

In [3]:
df = pd.read_csv(Data)

In [4]:
df.shape

(21547746, 9)

In [5]:
df.head(50)

,msno,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
0,YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=,41,30,129,129,1,20150930,20151101,0
1,AZtu6Wl0gPojrEQYB8Q3vBSmE2wnZ3hi1FbK1rQQ0A4=,41,30,149,149,1,20150930,20151031,0
2,UkDFI97Qb6+s2LWcijVVv4rMAsORbVDT2wNXF0aVbns=,41,30,129,129,1,20150930,20160427,0
3,M1C56ijxozNaGD0t2h68PnH2xtx5iO5iR2MVYQB6nBI=,39,30,149,149,1,20150930,20151128,0
4,yvj6zyBUaqdbUQSrKsrZ+xNDVM62knauSZJzakS9OW4=,39,30,149,149,1,20150930,20151121,0
5,KN7I82kjY0Tn76Ny95ncqBUVbO7b8AXrOPqZutKpxIM=,21,30,149,149,1,20150930,20151107,0
6,m5ptKif9BjdUghHXXomSezy5ohJiHm85PE13f/3kQaw=,39,30,149,149,1,20150930,20151128,0
7,uQxbyACsPOEkTIrv9jZgoGXelGBW81ZsSZKy9fhj5Z8=,39,30,149,149,1,20150930,20151125,0
8,LUPRfoE2r3WwVWhYO/TqQhjrL/qP6CO+/ORUlr7yNc0=,39,30,149,149,1,20150930,20151222,0
9,pMVjPLgVknaJYm9L0xUwxA2jmhpK7gfhGnsmmwX1mrE=,39,30,149,149,1,20150930,20151118,0
10,bQkbrEPdMfVfdsoz0RoWSmgYpHJuhRqtIml7aRUrFL8=,39,30,149,149,1,20150930,20151121,0
11,TZVCT9pCufI/AWjrG9s2fLbkpDI/8jRDAI6+PfQmTDs=,39,30,149,149,1,20150930,20151124,0
12,b2AiGMFhT6fbDyN12qnlALHKtj727HjUxCSGC9WeCi4=,39,30,149,149,1,20150930,20151117,0
13,ksInNb4D5jdSSIYUrNcoOJfAcrcNVxiMi8dAIMoh5cc=,39,30,149,149,1,20150930,20151129,0
14,aQKXNflQtXF92cpv4wxluXvUqJYy45NFy23kLYLSfgA=,39,30,149,149,1,20150930,20151111,0
15,iFxPpElVK6kXnZbuh5Di3ITpHtrkGNM73WbJG+zy05o=,39,30,149,149,1,20150930,20151122,0
16,8qrtRZQTuCih4YJhjEwvVdi9ojgltQnW5Rmqz3iMRXU=,39,30,149,149,1,20150930,20151106,0
17,pE2FeJOBZv5snDGdFuyQfDUenL8m84LB+gjG+njv0Dg=,39,30,149,149,1,20150930,20151114,0
18,vma4rQzDa/l4Wb/MyNxzI2YDuJIXlpL5xcw32BxaKLk=,39,30,149,149,1,20150930,20151123,0
19,Qw6UVFUknPVOLxSSsejinxU/8a5/AgmiWMvPoEt0rik=,39,30,149,149,1,20150930,20151108,0
20,G7TmHc9Gg2t8ovG/KFaB53We/0CQPELhZ5UUN2Ol3AQ=,39,30,149,149,1,20150930,20151113,0
21,T4XSZA0yn0xAe3pjL4PwR4Oi9KooBibT+S/3xmzEZLw=,39,30,149,149,1,20150930,20151119,0
22,pArK2x3bNZW0sAYaFg0h5c3xkx+2RhLa0RXG88jpt6I=,37,30,149,149,1,20151001,20151031,0
23,X3eZI5E4R0jhbOM5BVGe4V68OEmn/XMc84gds1W7H7o=,41,30,149,0,1,20151001,20151009,1
24,qNpZJ7gsMPAFSvc5V3kgqtFfUQU2SZe7XSUYOAfqtoA=,40,30,149,149,1,20151001,20151101,0
25,92L75JayJ2u+RZe0dp/tIuJjNqdnMlYum75v3zkD5oo=,40,30,149,149,1,20151001,20151101,0
26,WnxdSgeK3Vg4BIaioJQYilnL+E1SDxq+PZIwmmfTwgM=,34,0,0,149,1,20150930,20151031,0
27,ir1jh/vWZ932FpSC2WeMxdOHQ+OkuUo3ZPQs8Ms4J9g=,34,0,0,149,1,20150930,20151031,0
28,wZzIriSMn4Yh2sEU+yyPG+SEE/idQOSQhReC/zQwuXw=,34,0,0,149,1,20150930,20151031,0
29,6takVibQdMIXYkAUF/EhmVUE0Juzl1IzbmG4++BIquY=,34,0,0,149,1,20150930,20151031,0
30,dqg5vCoH2dRqfht4CzVLnQQ1fc4es4cQIXi2REYJYdc=,34,0,0,149,1,20150930,20151031,0
31,fhb3SHByTRWs/bFnhU2UTCG5s/82vqckWikHhoeAfao=,33,0,0,149,1,20150930,20151031,0
32,JMujk0BevyazsI4BPBBg46Ow+TFjD8rlsvxJ2a24qCo=,34,0,0,149,1,20150930,20151031,0
33,Pi2Tx2cryFAI+HmD5n3TPXpUBSW1mivpRPogWUzJBwY=,34,0,0,149,1,20150930,20151031,0
34,oUdU07An1vK8mOK2EdIksVYMpqy9AyvXDwXGLoB602g=,33,0,0,149,1,20150930,20151031,0
35,zw30zrUQUtiWnOYVEj4aMnLb13ENvOYtnnWq3bS9Yl0=,31,0,0,149,1,20150930,20151031,0
36,d1PEtagQ4nWCTT6MyGiFlpeNOU0oO3aDEtzTOrFjMZ0=,31,0,0,149,1,20150930,20151031,0
37,mUMKxpsLANbglV9/MOCn3hH25oRDAVc2M8uJHILiv8o=,34,0,0,149,1,20150930,20151031,0
38,UTP+ydXMSjGxjVcEsx5ykTKXY1TKlwcSUdKz8PrijEk=,33,0,0,149,1,20150930,20151031,0
39,r6lRYOz9dJ6uEXxSXiBPA+rk+ydbXsUoccyKb9GIxis=,33,0,0,149,1,20150930,20151031,0
40,dH8emkM3+1mffJShir8ozO9CHDgyke0/5KNDeZiVack=,33,0,0,149,1,20150930,20151031,0
41,MR8FWDGO+O0tzbF9O0CfrGgCtKuWdIBQ51+m/r50uhY=,33,0,0,149,1,20150930,20151031,0
42,9Q5TRzlJL3KhTp4Hogm3Y5IIlEp3fuXc/7K+Psphrx8=,31,0,0,149,1,20150930,20151031,0
43,o/7kLhrPCLGM9bhiD72KnzyESFAA8e0j0hQ5E0ZV6Uk=,23,0,0,149,1,20150930,20151031,0
44,FT4moGxOj6tzwkTSA0Iv9yzKOoyyHqEZ+f2uVrqCum8=,34,30,149,149,1,20151130,20151231,0
45,z1s1E/gm6xiwjNb8TSj1sQdXEUD9RMZ63it6cUdfhvQ=,34,30,149,149,1,20151130,20151231,0
46,lZyYiuAJW3qzDnicNBdlH1zTnqMQ0gbBBSYdJPL369Q=,34,30,149,149,1,20151130,20151231,0
47,pXpFcJbT8/FDkhnSUzNV3X2WTzUg5I4poa0+aJdIm/0=,34,30,149,149,1,20151130,20151231,0
48,0f9IUy6wP6pEUntXgu9PxCcieo1bNnzj/wxu9yfAZV4=,31,30,149,149,1,20151130,20151231,0
49,CAtxj/lcQ2WNyVwuO273wRLLFbRoNc6LiahqiIAKZnQ=,33,30,149,149,1,20151130,20151231,0

In [6]:
df.transaction_date.max()

np.int64(20170228)

In [7]:
check = df.loc[df['msno'] == '8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=' ]

In [8]:
check.shape

(19, 9)

In [9]:
check.head(26)

,msno,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
169159,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150108,20160209,0
1017364,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,35,7,0,0,0,20160225,20160325,0
1152764,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150108,20160311,0
1547139,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150308,20160606,0
3082786,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,0,0,149,1,20150508,20161006,0
5939436,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20160225,20160225,1
7258479,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20151225,20140308,1
8165630,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,0,0,149,1,20150508,20161106,0
9618255,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150608,20170105,0
10799003,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20151225,20140308,1
13528135,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150708,20170205,0
13939305,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150708,20170308,0
15104201,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150408,20160905,0
15924146,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150608,20161206,0
15933380,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150208,20160506,0
17645431,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20160208,20160308,0
18781204,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150308,20160707,0
20589654,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150408,20160806,0
21139787,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,41,30,149,149,1,20150208,20160408,0

In [10]:
check.transaction_date.min()

np.int64(20150108)

In [13]:
check.size

171